apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab-brussels
spec:
  chart:
    # https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/0.8.1/CHART_VERSIONS
    #version: "6.11.0" # GitLab 15.11.0
    version: "7.2.8" # GitLab v16.2.8
    #version: "7.4.1" # GitLab 16.4.1
    values:
      # Disable NGINX Ingress Controller.
      nginx-ingress:
        enabled: false
      global:
        # Configure the domain from the previous step.
        hosts:
          domain: apps.gitlab-2.bzj3.p1.openshiftapps.com
        ingress:
          # Unset `spec.ingressClassName` on the Ingress objects
          # so the OpenShift Router takes ownership.
          class: none
          annotations:
            # The OpenShift documentation says "edge" is the default, but
            # the TLS configuration is only passed to the Route if this annotation
            # is manually set.
            route.openshift.io/termination: "edge"